version: '2.4'

services:
  go_app:
    build: .
    command: ./main
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - .:/app

  postgres:
    image: postgres:11-alpine
    volumes:
      - postgres:/var/lib/psql
    ports:
    - 5432:5432

volumes:
  postgres: